#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-iterators
Version  : 1.0.8
Release  : 2
URL      : https://cran.r-project.org/src/contrib/iterators_1.0.8.tar.gz
Source0  : https://cran.r-project.org/src/contrib/iterators_1.0.8.tar.gz
Summary  : Provides Iterator Construct for R
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : clr-R-helpers

%description
No detailed description available

%prep
%setup -q -c -n iterators

%build

%install
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
R CMD INSTALL --install-tests --build  -l %{buildroot}/usr/lib64/R/library iterators
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library iterators


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/iterators/DESCRIPTION
/usr/lib64/R/library/iterators/INDEX
/usr/lib64/R/library/iterators/Meta/Rd.rds
/usr/lib64/R/library/iterators/Meta/hsearch.rds
/usr/lib64/R/library/iterators/Meta/links.rds
/usr/lib64/R/library/iterators/Meta/nsInfo.rds
/usr/lib64/R/library/iterators/Meta/package.rds
/usr/lib64/R/library/iterators/Meta/vignette.rds
/usr/lib64/R/library/iterators/NAMESPACE
/usr/lib64/R/library/iterators/R/iterators
/usr/lib64/R/library/iterators/R/iterators.rdb
/usr/lib64/R/library/iterators/R/iterators.rdx
/usr/lib64/R/library/iterators/doc/index.html
/usr/lib64/R/library/iterators/doc/iterators.R
/usr/lib64/R/library/iterators/doc/iterators.Rnw
/usr/lib64/R/library/iterators/doc/iterators.pdf
/usr/lib64/R/library/iterators/doc/writing.R
/usr/lib64/R/library/iterators/doc/writing.Rnw
/usr/lib64/R/library/iterators/doc/writing.pdf
/usr/lib64/R/library/iterators/examples/ifilter.R
/usr/lib64/R/library/iterators/examples/iforever.R
/usr/lib64/R/library/iterators/examples/ihasNext.R
/usr/lib64/R/library/iterators/examples/ilimit.R
/usr/lib64/R/library/iterators/examples/ipermn.R
/usr/lib64/R/library/iterators/examples/irecycle.R
/usr/lib64/R/library/iterators/examples/irep.R
/usr/lib64/R/library/iterators/examples/iseq.R
/usr/lib64/R/library/iterators/examples/itimer.R
/usr/lib64/R/library/iterators/examples/ivector.R
/usr/lib64/R/library/iterators/examples/ivector2.R
/usr/lib64/R/library/iterators/help/AnIndex
/usr/lib64/R/library/iterators/help/aliases.rds
/usr/lib64/R/library/iterators/help/iterators.rdb
/usr/lib64/R/library/iterators/help/iterators.rdx
/usr/lib64/R/library/iterators/help/paths.rds
/usr/lib64/R/library/iterators/html/00Index.html
/usr/lib64/R/library/iterators/html/R.css
/usr/lib64/R/library/iterators/unitTests/basicTest.R
/usr/lib64/R/library/iterators/unitTests/chunksizeTest.R
/usr/lib64/R/library/iterators/unitTests/iapplyTest.R
/usr/lib64/R/library/iterators/unitTests/icountnTest.R
/usr/lib64/R/library/iterators/unitTests/isplitTest.R
/usr/lib64/R/library/iterators/unitTests/recycleTest.R
/usr/lib64/R/library/iterators/unitTests/runTestSuite.sh
